import uuid
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.errors import ApiException
from app.core.time import utc_now
from app.models import Building, ComplianceReport
from app.schemas.admin import ComplianceReportRequest, ComplianceReportResponse, ComplianceReportStatusResponse
from app.services.admin import get_analytics
from app.services.storage import storage_path

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm
CONTENT_W = PAGE_W - 2 * MARGIN

NAVY       = colors.HexColor("#0A2947")
NAVY_LIGHT = colors.HexColor("#1E3A5F")
GRAY_DARK  = colors.HexColor("#1A1A1A")
GRAY_MID   = colors.HexColor("#555555")
GRAY_LIGHT = colors.HexColor("#888888")
ROW_ALT    = colors.HexColor("#F5F7FA")
BORDER     = colors.HexColor("#D0D5DD")
META_BG    = colors.HexColor("#E8EEF4")
STATUS_OK  = colors.HexColor("#0D6B2E")
STATUS_WARN = colors.HexColor("#92540A")
STATUS_FAIL = colors.HexColor("#9B1C1C")


def _naive_utc(value: datetime) -> datetime:
    return value.replace(tzinfo=None) if value.tzinfo else value


def _compliance_status(participation: float) -> tuple[str, object]:
    if participation >= 80:
        return "COMPLIANT", STATUS_OK
    elif participation >= 60:
        return "ATTENTION REQUIRED", STATUS_WARN
    else:
        return "NON-COMPLIANT", STATUS_FAIL


def _draw_page_frame(canvas, doc) -> None:
    """Renders a top rule, running header (page 2+), bottom rule, and footer."""
    canvas.saveState()
    page = doc.page

    # Top rule
    canvas.setStrokeColor(NAVY)
    canvas.setLineWidth(1.5)
    canvas.line(MARGIN, PAGE_H - 13 * mm, PAGE_W - MARGIN, PAGE_H - 13 * mm)

    # Running header on pages after the first
    if page > 1:
        canvas.setFont("Helvetica-Bold", 7.5)
        canvas.setFillColor(NAVY)
        canvas.drawString(MARGIN, PAGE_H - 9.5 * mm, "3MINUTES — SAFETY COMPLIANCE REPORT")
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(GRAY_LIGHT)
        canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 9.5 * mm, "CONFIDENTIAL")

    # Bottom rule
    canvas.setLineWidth(0.5)
    canvas.setStrokeColor(NAVY)
    canvas.line(MARGIN, 13 * mm, PAGE_W - MARGIN, 13 * mm)

    # Footer
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GRAY_LIGHT)
    canvas.drawString(MARGIN, 9 * mm, "Generated by 3MINUTES Safety Management System")
    canvas.drawCentredString(PAGE_W / 2, 9 * mm, "CONFIDENTIAL — FOR AUTHORIZED USE ONLY")
    canvas.drawRightString(PAGE_W - MARGIN, 9 * mm, f"Page {page}")

    canvas.restoreState()


def _formal_table_style(n_rows: int) -> TableStyle:
    cmds = [
        ("BACKGROUND",    (0, 0), (-1,  0), NAVY),
        ("TEXTCOLOR",     (0, 0), (-1,  0), colors.white),
        ("FONTNAME",      (0, 0), (-1,  0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1,  0), 8.5),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 9),
        ("TEXTCOLOR",     (0, 1), (-1, -1), GRAY_DARK),
        *[("BACKGROUND",  (0, r), (-1, r), ROW_ALT) for r in range(2, n_rows, 2)],
        # Grid + header underline
        ("GRID",          (0, 0), (-1, -1), 0.3, BORDER),
        ("LINEBELOW",     (0, 0), (-1,  0), 1.2, NAVY_LIGHT),
        # Padding
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 7),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 7),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]
    return TableStyle(cmds)


def _section_heading(number: str, title: str) -> list:
    style = ParagraphStyle(
        "SectionHead",
        fontName="Helvetica-Bold",
        fontSize=10.5,
        textColor=NAVY,
        spaceBefore=6,
        spaceAfter=4,
        leading=13,
    )
    return [
        HRFlowable(width=CONTENT_W, thickness=0.5, color=NAVY_LIGHT, spaceBefore=8, spaceAfter=4),
        Paragraph(f"{number}.  {title.upper()}", style),
    ]


def create_report(db: Session, body: ComplianceReportRequest, now: datetime | None = None) -> ComplianceReportResponse:
    now = now or utc_now()
    period_from, period_to = _naive_utc(body.period_from), _naive_utc(body.period_to)
    end_of_today = now.replace(hour=23, minute=59, second=59, microsecond=999999)
    if period_from >= period_to or period_to > end_of_today:
        raise ApiException(422, "VALIDATION_ERROR", "Periode compliance report tidak valid.")
    building = db.get(Building, settings.demo_building_id)
    if building is None:
        raise ApiException(503, "BUILDING_NOT_CONFIGURED", "Demo building belum dikonfigurasi.")

    report_id = str(uuid.uuid4())
    path = storage_path("reports", f"{report_id}.pdf")
    report = ComplianceReport(
        id=report_id,
        building_id=settings.demo_building_id,
        period_from=period_from,
        period_to=period_to,
        status="pending",
        file_url=f"/api/admin/compliance-reports/{report_id}/download",
        generated_at=now,
    )
    db.add(report)
    db.flush()
    try:
        analytics = get_analytics(db, period_from, period_to)
        _render_pdf(path, building.name, period_from, period_to, analytics, now, report_id)
        report.status = "ready"
        db.commit()
    except Exception:
        report.status = "failed"
        report.file_url = None
        report.error_message = "PDF generation failed"
        db.commit()
        raise ApiException(500, "PDF_GENERATION_FAILED", "Compliance report gagal dibuat.")
    return ComplianceReportResponse(report_id=report_id, status="ready")


def _render_pdf(
    path: Path,
    building_name: str,
    period_from: datetime,
    period_to: datetime,
    analytics,
    generated_at: datetime,
    report_id: str,
) -> None:
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=22 * mm,
        bottomMargin=22 * mm,
        title="3MINUTES Safety Compliance Report",
        author="3MINUTES Safety Management System",
        subject=f"Compliance Report {period_from:%Y-%m-%d} – {period_to:%Y-%m-%d}",
        creator="3MINUTES v1",
    )

    body = ParagraphStyle(
        "Body", fontName="Helvetica", fontSize=9.5,
        textColor=GRAY_DARK, leading=14, spaceAfter=3,
    )
    caption = ParagraphStyle(
        "Caption", fontName="Helvetica", fontSize=7.5,
        textColor=GRAY_LIGHT, leading=10, alignment=TA_CENTER,
    )
    meta_label = ParagraphStyle(
        "MetaLabel", fontName="Helvetica-Bold", fontSize=7.5,
        textColor=GRAY_MID, leading=10,
    )
    meta_value = ParagraphStyle(
        "MetaValue", fontName="Helvetica-Bold", fontSize=9,
        textColor=GRAY_DARK, leading=12,
    )
    kpi_label = ParagraphStyle(
        "KPILabel", fontName="Helvetica", fontSize=7.5,
        textColor=GRAY_MID, alignment=TA_CENTER, leading=10,
    )
    kpi_value = ParagraphStyle(
        "KPIValue", fontName="Helvetica-Bold", fontSize=22,
        textColor=NAVY, alignment=TA_CENTER, leading=26,
    )
    kpi_sub = ParagraphStyle(
        "KPISub", fontName="Helvetica", fontSize=7,
        textColor=GRAY_LIGHT, alignment=TA_CENTER, leading=9,
    )

    story = []

    cover = Table(
        [[
            Paragraph(
                '<font color="#FFFFFF" size="14"><b>3MINUTES</b></font><br/>'
                '<font color="#8BAECB" size="8">SAFETY MANAGEMENT SYSTEM</font>',
                ParagraphStyle("CoverL", leading=18, leftIndent=0),
            ),
            Paragraph(
                '<font color="#A0C8E8" size="8">OFFICIAL DOCUMENT</font><br/>'
                '<font color="#FFFFFF" size="10"><b>COMPLIANCE REPORT</b></font>',
                ParagraphStyle("CoverR", alignment=TA_RIGHT, leading=14),
            ),
        ]],
        colWidths=[CONTENT_W * 0.6, CONTENT_W * 0.4],
    )
    cover.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(cover)
    story.append(Spacer(1, 2 * mm))

    meta = Table(
        [
            [
                Paragraph("BUILDING", meta_label),
                Paragraph("REPORT PERIOD", meta_label),
                Paragraph("REPORT ID", meta_label),
                Paragraph("GENERATED (UTC)", meta_label),
            ],
            [
                Paragraph(building_name, meta_value),
                Paragraph(f"{period_from:%d %b %Y} – {period_to:%d %b %Y}", meta_value),
                Paragraph(report_id[:8].upper(), meta_value),
                Paragraph(f"{generated_at:%d %b %Y, %H:%M}", meta_value),
            ],
        ],
        colWidths=[
            CONTENT_W * 0.28,
            CONTENT_W * 0.30,
            CONTENT_W * 0.18,
            CONTENT_W * 0.24,
        ],
    )
    meta.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), META_BG),
        ("BACKGROUND",    (0, 1), (-1, 1), colors.white),
        ("GRID",          (0, 0), (-1, -1), 0.3, BORDER),
        ("LINEABOVE",     (0, 0), (-1,  0), 1.5, NAVY),
        ("LINEBELOW",     (0, 1), (-1, -1), 1.0, BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(meta)
    story.append(Spacer(1, 5 * mm))

    story.extend(_section_heading("1", "Executive Summary"))
    story.append(Spacer(1, 2 * mm))

    status_label, status_color = _compliance_status(analytics.participation_rate_percentage)
    badge = Table(
        [[Paragraph(
            f'<font color="#FFFFFF" size="10"><b>COMPLIANCE STATUS: {status_label}</b></font>',
            ParagraphStyle("Badge", alignment=TA_CENTER, leading=14),
        )]],
        colWidths=[CONTENT_W],
    )
    badge.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), status_color),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
    ]))
    story.append(badge)
    story.append(Spacer(1, 4 * mm))

    avg_s = analytics.average_shelter_time_ms / 1000
    kpi = Table(
        [[
            [
                Paragraph("PARTICIPATION RATE", kpi_label),
                Paragraph(f"{analytics.participation_rate_percentage:.1f}%", kpi_value),
                Paragraph("of registered residents", kpi_sub),
            ],
            [
                Paragraph("AVG. SHELTER TIME", kpi_label),
                Paragraph(f"{avg_s:.1f}s", kpi_value),
                Paragraph("per drill session", kpi_sub),
            ],
            [
                Paragraph("LOCATIONS TRACKED", kpi_label),
                Paragraph(str(len(analytics.heatmap_cells)), kpi_value),
                Paragraph("active zones in period", kpi_sub),
            ],
        ]],
        colWidths=[CONTENT_W / 3] * 3,
    )
    kpi.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#F8FAFB")),
        ("GRID",          (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(kpi)
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph(
        "This report summarizes emergency drill participation and evacuation performance for the "
        "specified reporting period. Compliance status is determined by the participation rate: "
        "≥ 80% = Compliant, 60–79% = Attention Required, < 60% = Non-Compliant. "
        "Data is collected automatically by the 3MINUTES Safety Management System.",
        body,
    ))

    story.extend(_section_heading("2", "Evacuation Trend Analysis"))
    story.append(Spacer(1, 2 * mm))

    trend_rows = [["WEEK", "AVERAGE EVACUATION TIME", "PERFORMANCE INDICATOR"]]
    for item in analytics.escape_route_trends:
        t_s = item["averageEvacuationTimeMs"] / 1000
        indicator = "Within target (≤ 180 s)" if t_s <= 180 else "Exceeds target (> 180 s)"
        trend_rows.append([item["period"], f"{t_s:.1f} seconds", indicator])
    if len(trend_rows) == 1:
        trend_rows.append(["No completed drills in period", "—", "—"])

    trend_table = Table(trend_rows, colWidths=[50 * mm, 65 * mm, 55 * mm])
    trend_table.setStyle(_formal_table_style(len(trend_rows)))
    story.append(trend_table)
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        "Performance target: average evacuation time ≤ 180 seconds per drill session.",
        caption,
    ))

    story.extend(_section_heading("3", "Location Safety Matrix"))
    story.append(Spacer(1, 2 * mm))

    heatmap_rows = [["LOCATION REFERENCE", "FAILURE RATE", "AVG. EVACUATION TIME", "SAMPLES"]]
    for cell in analytics.heatmap_cells:
        heatmap_rows.append([
            cell.location_ref,
            f"{cell.failure_rate_percentage:.1f}%",
            f"{cell.average_evacuation_time_ms / 1000:.1f} s",
            str(cell.sample_count),
        ])
    if len(heatmap_rows) == 1:
        heatmap_rows.append(["No location data available for period", "—", "—", "0"])

    heatmap_table = Table(
        heatmap_rows,
        colWidths=[65 * mm, 28 * mm, 52 * mm, 25 * mm],
    )
    heatmap_table.setStyle(_formal_table_style(len(heatmap_rows)))
    story.append(heatmap_table)
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        "Failure rate reflects the percentage of drill sessions that did not meet "
        "the accepted shelter threshold for each location.",
        caption,
    ))

    story.extend(_section_heading("4", "Certification"))
    story.append(Spacer(1, 2 * mm))

    story.append(Paragraph(
        "This is a system-generated compliance report produced by the 3MINUTES Safety Management "
        "System. The data presented reflects emergency drill and evacuation records stored in the "
        "system database for the specified reporting period. This report has not been manually edited "
        "and its contents are accurate to the data recorded in the system at the time of generation. "
        "Unauthorized reproduction or distribution of this document is prohibited.",
        body,
    ))
    story.append(Spacer(1, 5 * mm))

    cert = Table(
        [
            [
                Paragraph("ISSUING SYSTEM", meta_label),
                Paragraph("REPORT DATE", meta_label),
                Paragraph("CLASSIFICATION", meta_label),
            ],
            [
                Paragraph("3MINUTES Safety Management System v1", meta_value),
                Paragraph(f"{generated_at:%d %B %Y}", meta_value),
                Paragraph("CONFIDENTIAL", meta_value),
            ],
        ],
        colWidths=[CONTENT_W * 0.45, CONTENT_W * 0.28, CONTENT_W * 0.27],
    )
    cert.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), META_BG),
        ("GRID",          (0, 0), (-1, -1), 0.3, BORDER),
        ("LINEABOVE",     (0, 0), (-1,  0), 1.5, NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(cert)

    doc.build(story, onFirstPage=_draw_page_frame, onLaterPages=_draw_page_frame)


def get_report(db: Session, report_id: str) -> ComplianceReportStatusResponse:
    item = db.scalar(select(ComplianceReport).where(
        ComplianceReport.id == report_id,
        ComplianceReport.building_id == settings.demo_building_id,
    ))
    if item is None:
        raise ApiException(404, "REPORT_NOT_FOUND", "Compliance report tidak ditemukan.")
    return ComplianceReportStatusResponse(
        report_id=item.id, status=item.status,
        download_url=item.file_url if item.status == "ready" else None,
        generated_at=item.generated_at,
    )


def report_file(db: Session, report_id: str) -> Path:
    item = db.scalar(select(ComplianceReport).where(
        ComplianceReport.id == report_id,
        ComplianceReport.building_id == settings.demo_building_id,
        ComplianceReport.status == "ready",
    ))
    path = storage_path("reports", f"{report_id}.pdf")
    if item is None or not path.exists():
        raise ApiException(404, "REPORT_NOT_FOUND", "Compliance report belum tersedia.")
    return path
